/*C. Word on the Paper
time limit per test1 second
memory limit per test256 megabytes
On an 8×8
 grid of dots, a word consisting of lowercase Latin letters is written
vertically in one column, from top to bottom. What is it?

Input
The input consists of multiple test cases. The first line of the input contains
a single integer 𝑡 (1≤𝑡≤1000 ) — the number of test cases.

Each test case consists of 8
 lines, each containing 8
 characters. Each character in the grid is either .
 (representing a dot) or a lowercase Latin letter (𝚊
–𝚣
).

The word lies entirely in a single column and is continuous from the beginning
to the ending (without gaps). See the sample input for better understanding.

Output
For each test case, output a single line containing the word made up of
lowercase Latin letters (𝚊 –𝚣 ) that is written vertically in one column from
top to bottom.

Example
InputCopy
5
........
........
........
........
...i....
........
........
........
........
.l......
.o......
.s......
.t......
........
........
........
........
........
........
........
......t.
......h.
......e.
........
........
........
........
........
.......g
.......a
.......m
.......e
a.......
a.......
a.......
a.......
a.......
a.......
a.......
a.......
OutputCopy
i
lost
the
game
aaaaaaaa

*/
#include <iostream>
#include <string>
using namespace std;

int main() {
  int t;
  cin >> t;
  while (t--) {

    // get the word from the string
    // so traverse the string, if char is '.' then ignore
    // else append the char in ans;
    // return ans;
    string ans;
    for (int i = 0; i < 8; i++) {
      string s;
      cin >> s; // Read each row of the 8x8 grid
      for (char c : s) {
        if (c != '.') {
          ans += c; // Append non-dot characters to ans
        }
      }
    }
    cout << ans << endl;
  }
  return 0;
}

// sub: https://codeforces.com/problemset/submission/1850/308171839
