/*A. The Bento Box Adventure
time limit per test1 second
memory limit per test1024 megabytes
Image generated by ChatGPT 4o.
Boxed meals in Taiwan are very common, offering convenient and affordable
nutrition-balanced choices for students and office workers. These meals
typically include a variety of vegetables, protein, and rice, providing a
well-rounded diet. With numerous options available at local self-service
restaurants, they are a popular choice for those looking for a quick, healthy
lunch.

There are five Taiwanese self-service restaurants numbered from 1 to 5. You plan
to visit a different restaurant each day from Monday to Friday to pack a boxed
meal for lunch. You've already visited one restaurant from Monday to Thursday,
each time visiting a different one. Now, it's Friday, and you want to visit the
last remaining restaurant that you haven't been to yet this week.

Write a program that takes as input the four restaurants you've already visited
(one for each day from Monday to Thursday) and outputs the restaurant you should
visit on Friday.

Input
A single line of input containing four integers 𝑎,𝑏,𝑐,𝑑
, each between 1 and 5 (inclusive), representing the restaurant numbers you
visited from Monday to Thursday, in order.

1≤𝑎,𝑏,𝑐,𝑑≤5
All four numbers will be different.
Output
Output the restaurant number you should visit on Friday.

Examples
InputCopy
1 3 2 5
OutputCopy
4
InputCopy
2 5 4 3
OutputCopy
1


*/

#include <iostream>
int main() {
  bool v[6] = {0};
  for (int i = 0; i < 4; i++) {
    int x;
    std::cin >> x;
    v[x] = 1;
  }
  for (int i = 1; i < 6; i++) {
    if (!v[i]) {
      std::cout << i << std::endl;
      break;
    }
  }
  return 0;
}
// sub: https://codeforces.com/problemset/submission/2041/323902038
